# see http://docs.travis-ci.com/user/languages/r/
language: r

# Be strict when checking our package
warnings_are_errors: true

# before_script:
#  - wget http://poppler.freedesktop.org/poppler-0.32.0.tar.xz
#  - tar poppler-0.32.0.tar.xz
#  - export PATH=$PATH:$PWD/poppler-0.32.0

before_install:
  - sudo apt-get install -qq poppler-utils

# install:
#  - wget http://poppler.freedesktop.org/poppler-0.32.0.tar.xz
#  - tar -xJf poppler-0.32.0.tar.xz
#  - cd poppler-0.32.0 && ./configure --prefix=/usr && make && make install

# Use github version of testthat
r_github_packages:
 - hadley/testthat
 - romainfrancois/bibtex
 - jimhester/covr

# remove default --as-cran so testthat tests are run (also avoids to useless check notes)
r_check_args:

notifications:
  email:
    recipients:
      - mathew.w.mclean@gmail.com
    on_success: change # always|never|change, default: change
    on_failure: always # default: always

after_success:
 - Rscript -e 'library(covr);coveralls()'